import { defineArrayMember, defineField, defineType } from "sanity";

const seo = defineType({ name: "seo", title: "SEO", type: "object", fields: [defineField({ name: "title", title: "SEO title", type: "string", validation: rule => rule.max(60) }), defineField({ name: "description", title: "SEO description", type: "text", rows: 3, validation: rule => rule.max(160) }), defineField({ name: "ogImage", title: "OG image", type: "image", options: { hotspot: true } })] });
const image = defineField({ name: "image", title: "Ảnh", type: "image", options: { hotspot: true }, fields: [defineField({ name: "alt", title: "Alt text", type: "string" })] });
const protocolStep = defineType({ name: "protocolStep", title: "Bước quy trình", type: "object", fields: [defineField({ name: "step", title: "Thứ tự", type: "number", validation: rule => rule.required().integer().min(1) }), defineField({ name: "title", title: "Tiêu đề bước", type: "string", validation: rule => rule.required() }), defineField({ name: "description", title: "Mô tả", type: "text", rows: 3 })], preview: { select: { step: "step", title: "title" }, prepare: ({ step, title }) => ({ title: `${step}. ${title}` }) } });
const location = defineType({ name: "location", title: "Cơ sở", type: "object", fields: [defineField({ name: "name", title: "Tên cơ sở", type: "string", validation: rule => rule.required() }), defineField({ name: "address", title: "Địa chỉ", type: "string", validation: rule => rule.required() }), defineField({ name: "mapUrl", title: "Link Google Maps", type: "url" }), defineField({ name: "isPrimary", title: "Cơ sở chính", type: "boolean", initialValue: false })], preview: { select: { title: "name", subtitle: "address" } } });
const service = defineType({ name: "service", title: "Dịch vụ", type: "document", fields: [defineField({ name: "title", title: "Tên dịch vụ", type: "string", validation: rule => rule.required() }), defineField({ name: "slug", title: "URL slug", type: "slug", options: { source: "title" }, validation: rule => rule.required() }), defineField({ name: "description", title: "Mô tả", type: "text", rows: 4 }), defineField({ name: "isPrimary", title: "Dịch vụ nổi bật", type: "boolean", initialValue: false }), defineField({ name: "treatments", title: "Liệu pháp liên quan", type: "array", of: [defineArrayMember({ type: "reference", to: [{ type: "treatment" }] })] }), defineField({ name: "seo", title: "SEO", type: "seo" })] });
const treatment = defineType({ name: "treatment", title: "Liệu pháp", type: "document", fields: [defineField({ name: "title", title: "Tên liệu pháp", type: "string", validation: rule => rule.required() }), defineField({ name: "slug", title: "URL slug", type: "slug", options: { source: "title" }, validation: rule => rule.required() }), defineField({ name: "shortDescription", title: "Mô tả ngắn", type: "text", rows: 3 }), defineField({ name: "description", title: "Mô tả chi tiết", type: "text", rows: 5 }), defineField({ name: "duration", title: "Thời lượng", type: "string" }), defineField({ name: "price", title: "Giá (VNĐ)", type: "number", validation: rule => rule.min(0) }), defineField({ name: "isPopular", title: "Liệu pháp phổ biến", type: "boolean", initialValue: false }), image, defineField({ name: "benefits", title: "Lợi ích", type: "array", of: [defineArrayMember({ type: "string" })] }), defineField({ name: "protocols", title: "Quy trình thực hiện", type: "array", of: [defineArrayMember({ type: "protocolStep" })] }), defineField({ name: "seo", title: "SEO", type: "seo" })], preview: { select: { title: "title", subtitle: "shortDescription", media: "image" } } });
const post = defineType({ name: "post", title: "Bài viết", type: "document", fields: [defineField({ name: "title", title: "Tiêu đề", type: "string", validation: rule => rule.required() }), defineField({ name: "slug", title: "URL slug", type: "slug", options: { source: "title" }, validation: rule => rule.required() }), defineField({ name: "excerpt", title: "Tóm tắt", type: "text", rows: 3 }), defineField({ name: "category", title: "Chuyên mục", type: "string" }), defineField({ name: "publishedAt", title: "Ngày xuất bản", type: "datetime" }), image, defineField({ name: "body", title: "Nội dung", type: "text", rows: 10 }), defineField({ name: "seo", title: "SEO", type: "seo" })], preview: { select: { title: "title", subtitle: "category", media: "image" } } });
const testimonial = defineType({ name: "testimonial", title: "Cảm nhận khách hàng", type: "document", fields: [defineField({ name: "quote", title: "Trích dẫn", type: "text", validation: rule => rule.required() }), defineField({ name: "context", title: "Bối cảnh khách hàng", description: "Ví dụ: “Vận động viên chuyên nghiệp”, hoặc mô tả ngắn về khách hàng", type: "string" }), defineField({ name: "avatar", title: "Ảnh đại diện", type: "image", options: { hotspot: true } }), defineField({ name: "rating", title: "Đánh giá (1-5 sao)", type: "number", validation: rule => rule.integer().min(1).max(5) })], preview: { select: { title: "context", subtitle: "quote", media: "avatar" } } });
const faq = defineType({ name: "faq", title: "Câu hỏi thường gặp", type: "document", fields: [defineField({ name: "question", title: "Câu hỏi", type: "string", validation: rule => rule.required() }), defineField({ name: "answer", title: "Trả lời", type: "text", rows: 4 }), defineField({ name: "order", title: "Thứ tự", type: "number" })], orderings: [{ name: "orderAsc", title: "Thứ tự hiển thị", by: [{ field: "order", direction: "asc" }] }], preview: { select: { title: "question", subtitle: "order" } } });
const siteSettings = defineType({ name: "siteSettings", title: "Thiết lập website", type: "document", fields: [defineField({ name: "siteUrl", title: "Website URL", type: "url" }), defineField({ name: "contactPhone", title: "Số điện thoại", type: "string" }), defineField({ name: "contactEmail", title: "Email", type: "string" }), defineField({ name: "locations", title: "Cơ sở", type: "array", of: [defineArrayMember({ type: "location" })] }), defineField({ name: "socialMedia", title: "Mạng xã hội", type: "object", fields: [defineField({ name: "facebook", title: "Facebook URL", type: "url" }), defineField({ name: "instagram", title: "Instagram URL", type: "url" }), defineField({ name: "zalo", title: "Zalo ID", type: "string" })] }), defineField({ name: "seo", title: "SEO mặc định", type: "seo" })], preview: { prepare: () => ({ title: "Thiết lập website" }) } });

export const schemaTypes = [seo, protocolStep, location, siteSettings, service, treatment, post, testimonial, faq];
